import Head from "next/head";
import Hero from "@/components/hreo/hero";
import Heading from "@/components/heading/heading";
import Container from "@/components/container/container";
import Postcard from "@/components/postcard/postcard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mediumsh-blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero />

        <Heading heading="Recent Posts" />

        <div>
          <Postcard column />
        </div>
      </Container>
    </>
  );
}
