import Head from "next/head";
import Hero from "@/components/hreo/hero";
import Container from "@/components/container/container";
import Featuredposts from "@/components/posts/featuredposts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mediumy-blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero />
        <Featuredposts column heading="Recent Posts"  />
      </Container>
    </>
  );
}
